---
- hosts: runner
  gather_facts: no
  become: no

  tasks:
    - name: grep guest IP address
      command: awk -F "=" '/guest_ip/ {print $2}' kite-deploy/inventory
      register: result_ip

    - debug:
        var: result_ip.stdout

    - name: add guest IP into guest group
      community.general.ini_file:
        path: "inventory"
        section: guest
        option: "{{ result_ip.stdout }}"
        allow_no_value: yes

    - name: grep instance id/name
      command: awk -F "=" '/instance/ {print $2}' kite-deploy/inventory
      register: result_instance

    - debug:
        var: result_instance.stdout

    - name: add instance id/name into guest group vars
      community.general.ini_file:
        path: "inventory"
        section: guest:vars
        option: instance
        value: "{{ result_instance.stdout }}"
        allow_no_value: yes

    - name: grep resource group group name
      command: awk -F "=" '/resource_group_name/ {print $2}' kite-deploy/inventory
      register: result_resource_group
      when: cloud_platform == "azure"

    - debug:
        var: result_resource_group.stdout
      when: cloud_platform == "azure"

    - name: add resource group name into guest group vars
      community.general.ini_file:
        path: "inventory"
        section: guest:vars
        option: resource_group_name
        value: "{{ result_resource_group.stdout }}"
        allow_no_value: yes
      when: cloud_platform == "azure"
